# The approximate line length for printing.
# This is used as a guide to determine when to wrap lines,
# but note this is not a hard upper bound. Defaults to 120
column_width = 120

# The type of line endings to use, supports either `Unix` (LF) or `Windows` (CRLF) options.
line_endings = "Unix"

# The type of indents to use, supports either `Tabs` or `Spaces`
indent_type = "Spaces"

# The width of spaces a single indent level should be.
# This option is ignored if the `indent_type` is set to `Tabs`.
indent_width = 4

# set this to true to force convert single quoted string to double quoted string.
force_double_quote = false